### ISSUE TITLE
Can't erase text in text knob on macOS

### ISSUE THREAD

**Issue by tivorreda64** [ookami-kb/storybook_flutter#73]
Hi there! 
I'm having a strange problem with text field knobs when building for macOS and android emulators on macOS.
When I try to erase a text in a text knob with backspace or delete, the text just won't change. I can write texts but can't erase them, can't move the cursor with the keyboard arrows either.

On web build it works just fine.

Is something missing in my project setup?

Thanks!

#### Code sample
```dart
import 'package:flutter/material.dart';
import 'package:storybook_flutter/storybook_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Storybook(
      stories: [
        Story(
          name: 'TestWidget',
          builder: (context) => Center(
            child: Text(
              context.knobs.text(
                label: 'Input text',
                initial: 'Default text',
              ),
            ),
          ),
        ),
      ],
    );
  }
}

```

#### Versions
- Flutter: stable 2.10.2
- macOS: 11.6
- Dart: 2.16.1
- storybook_flutter: 0.10.1+1

#### Flutter Doctor
```
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6 20G165 darwin-x64, locale en)
    • Flutter version 2.10.2 at /Users/vitorreda/Downloads/flutter 2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (6 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vitorreda/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • SM N9600 (mobile) • 25fb3b8227047ece • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by ookami-kb** [comment]
Hi,

That's actually weird, it should work without it. I'll take a look, thanks for the investigation!

**Comment by mgesmundo** [comment]
Hello,
I've the same problem. Any news about it?
Thanks

**Comment by ookami-kb** [comment]
Hey, didn't have time at all 🤷 

I'll try to take a look in the near future. Does the solution with `CupertinoApp` work for you as well?

**Comment by buehler** [comment]
Maybe I can shine some light on the issue. I ran into the same error. Somehow I even encounter this in a normal Flutter app.

The error message thrown is:
```
════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#901fb(logicalKey: LogicalKeyboardKey#e3a44(keyId: "0x200000106", keyLabel: "Meta Left", debugName: "Meta Left"), physicalKey: PhysicalKeyboardKey#f2ed2(usbHidUsage: "0x000700e3", debugName: "Meta Left"), repeat: false) and its data: RawKeyEventDataWindows#49e75(keyCode: 91, scanCode: 57435, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
raw_keyboard.dart:1
Failed assertion: line 683 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      RawKeyboard.handleRawKeyEvent
raw_keyboard.dart:683
#3      KeyEventManager.handleRawKeyMessage
hardware_keyboard.dart:951
#4      BasicMessageChannel.setMessageHandler.<anonymous closure>
platform_channel.dart:214
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
binding.dart:393
#6      _invoke2 (dart:ui/hooks.dart:183:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:130:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
Unable to parse JSON message:
The document is empty.


```
